# Permalinks
permalink:           pretty

# Setup
title:               <MBLance>
tagline:             Data Modeling
url:                 http://mblance.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Buck
  url:               mblance.com
  email:             matt@mblance.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mblance

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
